### ISSUE TITLE
PASTA: will not retrieve the full DOI

### ISSUE THREAD

**Issue by isangil** [lter/deims#116]
Per report from J.L (woods Hole)

Before I dig deeper I am wondering if you have ever seen where the DOI is only partially retrieved.  I used VBO to retrieve the DOI and get only 10.6073/pasta/2ae057a80d when it should have been 10.6073/pasta/2ae057a80dfc191ba3638ee41aa6a729

**Comment by isangil** [comment]
Dave Reid encoded this helper in the PastaAPI 

 public function fetchDOI() {
        list($scope, $identifier, $revision) = $this->dataSet->getPackageIDParts();
        $url = static::getApiUrl("package/doi/eml/{$scope}/{$identifier}/{$revision}");
        $request = drupal_http_request($url, array('timeout' => 10));
        if (empty($request->error) && $request->code == 200 && !empty($request->data)) 
          if (preg_match('/doi:([\d.]+\/pasta\/[a-e0-9]+)/', $request->data, $matches)) {
            return $matches[1];
          }
...

**Comment by isangil** [comment]
The JL followed up, spotting the problem

"After adding an Exception message before the preg_match I can see that it was getting the DOI.
But with (preg_match('/doi:([\d.]+\/pasta\/[a-e0-9]+)/', $request->data, $matches)) it would cut out anything above 'e'  so put in 'z' and it works. e.g. (preg_match('/doi:([\d.]+\/pasta\/[a-z0-9]+)/', $request->data, $matches))

Was there a reason for only only a-e?"

**Comment by isangil** [comment]
And No, there is no reason to stop at "e".... this was a typo.

**Comment by davereid** [comment]
Oh my gosh, no, it should include 'f' as well.

**Comment by isangil** [comment]
:)

**Comment by isangil** [comment]
fix with this very elaborate and arduous commit
https://github.com/lter/deims/commit/235c86c894c62c71323cd4655d3bde1979df2de0
