### ISSUE TITLE
Code Climate: Unused variables - investigate

### ISSUE THREAD

**Issue by isangil** [lter/deims#126]
Here is a sleuth of improvable work found using code climate. This is in the bug risk category, ran with help by Joseph Purcell. Results at https://codeclimate.com/github/josephdpurcell/deims/issues?category=bugrisk&engine=
...
  $name = $variable['name'];
Found in modules/custom/deims_data_explorer/deims_data_explorer.pages.inc by phpmd
Avoid unused local variables such as '$key'.
  foreach ($form_state['values'] as $key => $value) {
Found in modules/custom/deims_data_explorer/deims_data_explorer.pages.inc by phpmd
Avoid unused local variables such as '$value'.
  foreach ($form_state['values'] as $key => $value) {
Found in modules/custom/deims_data_explorer/deims_data_explorer.pages.inc by phpmd
Avoid unused local variables such as '$unitmetatada'.
              $unitmetatada['minimum'] =  $item['data']['minimum'];
Found in modules/custom/deims_variable/deims_variable.field.inc by phpmd
Avoid unused local variables such as '$entity'.
  foreach ($entities as $id => $entity) {
Found in modules/custom/deims_variable/deims_variable.field.inc by phpmd
Avoid unused local variables such as '$delta'.
  $delta = $context['delta'];
Found in modules/custom/deims_variable/deims_variable.field.inc by phpmd
Avoid unused local variables such as '$items'.
  $items = $context['items'];
Found in modules/custom/deims_variable/deims_variable.field.inc by phpmd
Avoid unused local variables such as '$instance'.
  foreach ($instances as $field_name => $instance) {
Found in modules/custom/deims_variable_search/deims_variable_search.module by phpmd
Avoid unused local variables such as '$attributes'.
    foreach ($field['columns'] as $column => $attributes) {
Found in modules/custom/deims_variable_search/deims_variable_search.module by phpmd
Avoid unused local variables such as '$instance'.
  foreach ($instances as $field_name => $instance) {
Found in modules/custom/deims_variable_search/deims_variable_search.module by phpmd
Avoid unused local variables such as '$instance'.
  foreach ($instances as $field_name => $instance) {
Found in modules/custom/deims_variable_search/deims_variable_search.module by phpmd
Avoid unused local variables such as '$label'.
  $label = entity_label($entity_type, $entity);
Found in modules/custom/eml_harvest_list/eml_harvest_list.module by phpmd
Avoid unused local variables such as '$request'.
    $request = drupal_http_request($url, array('method' => 'DELETE'));
Found in modules/custom/pasta/lib/PastaApi.php by

**Comment by lukewertz** [comment]
Unused local variables are super easy to clean up and generally present a very low risk. Good find.

**Comment by isangil** [comment]
Small world, Luke.  Joseph tells me you are good friends.  

I´ll do some scrubbing.  Some things (not above) remarked by Code Climate seem borderline opinionated things, but there is value in consistency.  Should not take long to make it better.

**Comment by isangil** [comment]
some vars i felt conf. eliminating here
https://github.com/lter/deims/commit/6524f5ef803034c94e9dab8b8ea7d2c35e73485f
