### ISSUE TITLE
ORCID ID - add new field in person

### ISSUE THREAD

**Issue by jlaundre** [lter/deims#152]
Need to add afield for an ORCID id into the person content

**Comment by isangil** [comment]
agree - this could be a nice add-on for those who use ORC-IDs.  I am not sure how much of the ORC-ID is a fad or whether is taking the academia by storm, so long-term is a question mark.  However, it is not a dramatic change, and the level of effort should be minimal.

Is there a recommendation on how to express the ORCIDs in the XML-standard feeds in any way?  

Incidentally, the ILTER has been using ORCIDS in their DEIMS instances for over two years now, in case you want to see their implementation (no rocket science, I am afraid)

**Comment by jlaundre** [comment]
Hi Inigo, 

I forgot to add that to output it as EML one would need to: 


Enabled it in the EML tab of Managed Display as "EML onlineUrl" and moved it below the URL field. 


Modified the eml--node--person.tpl.php (file in profiles/deims/modules/custom/eml/templates) by adding the following: 

<?php $orcid=render($content['field_orcid_id']); 
$onlineurl_tags = array("<onlineUrl>","</onlineUrl>"); 
$userid_tags = array("<userId directory=\" http://orcid.org \">","</userId>"); 
print str_replace($onlineurl_tags,$userid_tags,$orcid); ?> 



I had not figured out how to have the feature export the above settings. I meant to do a pull request but did a pull instead. 

Jim 

----- Original Message -----
