### ISSUE TITLE
Second line of address of person is not added to eml

### ISSUE THREAD

**Issue by jlaundre** [lter/deims#154]
The second line of a person's address is not added to the eml address field.

**Comment by jlaundre** [comment]
Eml person address is missing 2nd line of address

Eml output only the first line of the address stored in the person content.  Need to add code in eml module eml.field.inc to check if there is a second line and then concatenated the two, separating them by a comma.

        if (!empty($item['premise'])) {
          $address['deliveryPoint'] = $address['deliveryPoint'].", ".$item['premise'];  
        }

**Comment by isangil** [comment]
makes sense

**Comment by isangil** [comment]
do you wanna write a patch & make a pull request? ill be happy to review and commit

**Comment by jlaundre** [comment]
Hi Inigo,

Yes I will.  I have been working on getting a number of fixes in github, e.g. http://arc-lter.ecosystems.mbl.edu/repopulating-cachelterunit-table
And in EmlDataSet.php adding utf8 option to tidy statement at line 80, i.e. $tidy->repairString($xml, $config,'utf8') for &nbsp problem.


Jim

**Comment by jlaundre** [comment]
No more comments from users
