### ISSUE TITLE
drush site-install fails with default Package ID pattern

### ISSUE THREAD

**Issue by rraub** [lter/deims#30]
When running the site install from drush (6.2.0) for deims:

```
> drush site-install deims --db-url=mysql://root:root@localhost/deims --site-name=Example
...

WD php: Exception: The Package ID pattern is using the following invalid tokens: [node:field_data_set_id], [node:field_eml_revision_id].
```

I'm assuming the [default value for the Package ID](https://github.com/lter/deims/blob/9db5d18b9096a788debd12f933222fee209adc95/modules/custom/eml/eml.module#L364) is referencing tokens that haven't been defined yet, but I'm just guessing. 

It isn't complaining about the station-acronym token and that one is defined in the [deims.tokens.inc](https://github.com/lter/deims/blob/9db5d18b9096a788debd12f933222fee209adc95/deims.tokens.inc#L13)

**Comment by davereid** [comment]
Hrm, those tokens _should_ exist for sure, but it might be an installation order issue due to Features having to create those fields. Pull request #31 is not the right solution as it will actually prevent the tokens from working correctly under normal circumstances. I can try and do some debugging and figure out why they aren't available in install. As a last resort we can just disable the validation on that tokenized text field if being run on install.

**Comment by isangil** [comment]
Ryan, did you try installing the site the old-school way? I'd recommend once you are done with 'drush make', to point your browser to the site URL and install from there.  While a bit slower, you'll probably have more chances of success.

**Comment by rraub** [comment]
I have tried installing the manual way using the web interface and when I submit the 'Setup a Database' step it builds me the 31 standard Drupal tables and returns me to the same page (with these additional GET parameters &op=start&id=1). It also writes the sites/default/settings.php file but thats as far as it gets. 

This was repeatable with todays 7.x-1.x branch and with Drush 6.2.0, php 5.5.3 (with no op-cache) and there is nothing logged about it.

Are either of these behaviors reproducible by anyone else?

**Comment by davereid** [comment]
It definitely might be PHP specific. I'm using PHP 5.4.17 and I can install
correctly after running make. I'm not 100% sure on the status of Drupal 7
and the various contrib modules being compatible with PHP 5.5.

**Comment by isangil** [comment]
Ryan,
Sorry for the hassle!
PHP 5.5 is definitely advanced PHP -- i dont own any instance running that level, and i requested a Sevilleta sysadmin contractor not to go with 5.5 a couple of weeks ago cause of the fear something may fail.    

However, how about the php.ini, are you giving php ample resources to process the install?  These are perhaps a bit of an overkill, but here are some key parameters...

max_execution_time = 230
max_input_time = 180
memory_limit = 512M

**Comment by isangil** [comment]
I installed on Friday, I didnt see any problems.

Linux 2 2.6.32-45-generic
Apache/2.2.14 (Ubuntu)
PHP/5.3.2-1ubuntu4.22

etc..

**Comment by rraub** [comment]
Using the php settings above, I've run some tests manually installing deims with various versions of php:
5.2.17 - succeeds 
5.3.28 - succeeds 
5.4.4 - succeeds 
5.4.17 - @davereid has reported success 
5.4.19 - fails 
5.5.3 - fails

This was all done on Apache 2.2.25, OS X 10.9.2.

Digging through the php change log (http://php.net/ChangeLog-5.php) looking at 5.4.18 and 5.4.19.
https://bugs.php.net/bug.php?id=62672  looks like its the most likely culprit, but thats nothing more than a wild speculation.

**Comment by isangil** [comment]
That is useful info, Ryan.  we can make a note, as there will be more folks trying to build or install with versions of PHP newer that 5.4.4

I will re-test to confirm around 5.4.4 before making a note on requisites/install/README

Thanks! Inigo

**Comment by isangil** [comment]
Hum... I just build the latest DEIMS using 'git clone' + 'drush make' on a system with php 5.5.  I have seen a slowdown of the install around the module 'taxonomy', but other than that, seems fine.  i tested the dataset form (the rendering part) and seems OK thus far.

-Ubuntu 14.04 LTS
- Apache/2.4.7
- mysql  5.5.38
- PHP 5.5.9

will  keep this open, see whether i find oddities.

**Comment by isangil** [comment]
Closed due to inactivity
